name: Catch this
favicon: null
layout_spectrum: 0.49878450646065176
typography_spectrum: 0.34103302797302604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4375
  lightness: 0.9013375968206674
  saturation: 0.28483387106098235
  rhythmicContrast: 0.777347061317414
purpose: []
