title: The I-Course
cta:
  domain: null
  version: null
  bucket: null
layout_spectrum: 0.4987845064606518
favicon: null
name: Catch this
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4375
  lightness: 0.8021277
  saturation: 0.6042553
  rhythmicContrast: 0.3212766
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.341033027973026
